name: myexpenseproject
description: A new Flutter project.

publish_to: "none" # Remove this line if you want to publish the app

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  uuid: ^4.3.3
  intl: ^0.20.2
  fl_chart: ^0.71.0
  animate_do: ^4.2.0
  google_fonts: ^6.2.1
  # firebase_core: ^2.15.0 # Correct version for Firebase Core
  # firebase_auth: ^4.10.0 # Correct version for Firebase Auth
  js: ^0.6.7
  firebase_core: ^2.24.0
  firebase_auth: ^4.17.0
  firebase_auth_web: ^5.8.13
  firebase_core_web: ^2.13.0
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
